default:
  image: node:latest

stages:
  - test

variables:
  JAVA_HOME: '/usr/lib/jvm/java-11-openjdk-amd64'
  ANDROID_HOME: '/opt/android/sdk'

before_script:
  - export JAVA_HOME=$JAVA_HOME
  - export PATH=$JAVA_HOME/bin:$PATH
  - export ANDROID_HOME=$ANDROID_HOME
  - export PATH=$ANDROID_HOME/platform-tools:$ANDROID_HOME/tools:$PATH

unit-tests:
  image: node:lts
  stage: test
  only:
    - master
  before_script:
    - npm ci
  script:
    - npm run test:ci
  artifacts:
    paths:
      - coverage/
      - test-results/

detox_test:
  stage: test
  image: node:lts
  only:
    - master
  script:
    - echo $JAVA_HOM
    - npm install -g detox-cli
    - npm ci
    - npm run detox:build:android
    - npm run detox:test:android
