default:
  image: node:latest

stages:
  - test

unit-tests:
  image: node:lts
  stage: test
  only:
    - master
  before_script:
    - npm ci
  script:
    - npm run test:ci
  artifacts:
    paths:
      - coverage/
      - test-results/
