enum ActionTypes {
  API_CALL_REQUEST = 'API_CALL_REQUEST',
  API_CALL_FAILURE = 'API_CALL_FAILURE',
  API_CALL_SUCCESS = 'API_CALL_SUCCESS',
  SUCCESS_OPERATION = 'SUCCESS_OPERATION',
  LOGIN_REQUEST = 'LOGIN_REQUEST',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGOUT = 'LOGOUT',
  LOGOUT_SUCCESS = 'LOGOUT_SUCCESS',
  GET_HOTELS = 'GET_HOTELS',
  SET_HOTELS = 'SET_HOTELS',
  SELECT_HOTEL = 'SELECT_HOTEL',
  UPDATE_RESERVATION = 'UPDATE_RESERVATION',
  SAVE_ACCOUNT = 'SAVE_ACCOUNT',
  ADD_CARD = 'ADD_CARD',
}

export default ActionTypes;
